# Task
Install pyspark and initialize a spark session in Google Colab.

## Install pyspark

### Subtask:
Install the necessary libraries for PySpark in Google Colab.


**Reasoning**:
The subtask requires installing pyspark and findspark libraries. Using pip install in a code block will accomplish this.



In [1]:
!pip install pyspark findspark

## Initialize spark session

### Subtask:
Initialize a Spark session to start using Spark functionalities.


**Reasoning**:
Initialize a Spark session as instructed.



In [2]:
import findspark
findspark.init()
from pyspark.sql import SparkSession
spark = SparkSession.builder.getOrCreate()

## Summary:

### Data Analysis Key Findings

*   The `pyspark` library was already installed in the environment.
*   The `findspark` library was successfully installed.
*   A Spark session was successfully initialized and is ready for use.

### Insights or Next Steps

*   The environment is set up to begin using PySpark for data analysis.
*   The next step is to load and process data using the initialized Spark session.


In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("/content/drive/MyDrive/TerraTrend/house_prices.csv")

In [3]:
pd.set_option('display.max_rows', None)#This line sets that all rows will be shown regardless of how many there are.

pd.set_option('display.max_columns', None)#This line sets that all rows will be shown regardless of how many there are

In [4]:
df.head()


Index                                              Title  \
0      0  1 BHK Ready to Occupy Flat for sale in Srushti...   
1      1  2 BHK Ready to Occupy Flat for sale in Dosti V...   
2      2  2 BHK Ready to Occupy Flat for sale in Sunrise...   
3      3        1 BHK Ready to Occupy Flat for sale Kasheli   
4      4  2 BHK Ready to Occupy Flat for sale in TenX Ha...   

                                         Description Amount(in rupees)  \
0  Bhiwandi, Thane has an attractive 1 BHK Flat f...           42 Lac    
1  One can find this stunning 2 BHK flat for sale...           98 Lac    
2  Up for immediate sale is a 2 BHK apartment in ...          1.40 Cr    
3  This beautiful 1 BHK Flat is available for sal...           25 Lac    
4  This lovely 2 BHK Flat in Pokhran Road, Thane ...          1.60 Cr    

   Price (in rupees) location Carpet Area         Status         Floor  \
0             6000.0    thane    500 sqft  Ready to Move  10 out of 11   
1            13799.0    thane    473 sqft  Ready to Move   3 out of 22   
2            17500.0    thane    779 sqft  Ready to Move  10 out of 29   
3                NaN    thane    530 sqft  Ready to Move    1 out of 3   
4            18824.0    thane    635 sqft  Ready to Move  20 out of 42   

  Transaction      Furnishing facing             overlooking  \
0      Resale     Unfurnished    NaN                     NaN   
1      Resale  Semi-Furnished   East             Garden/Park   
2      Resale     Unfurnished   East             Garden/Park   
3      Resale     Unfurnished    NaN                     NaN   
4      Resale     Unfurnished   West  Garden/Park, Main Road   

                               Society Bathroom Balcony Car Parking  \
0  Srushti Siddhi Mangal Murti Complex        1       2         NaN   
1                          Dosti Vihar        2     NaN      1 Open   
2                 Sunrise by Kalpataru        2     NaN   1 Covered   
3                                  NaN        1       1         NaN   
4          TenX Habitat Raymond Realty        2     NaN   1 Covered   

              Ownership Super Area  Dimensions  Plot Area  
0                   NaN        NaN         NaN        NaN  
1              Freehold        NaN         NaN        NaN  
2              Freehold        NaN         NaN        NaN  
3                   NaN        NaN         NaN        NaN  
4  Co-operative Society        NaN         NaN        NaN

In [5]:
df.shape

(187531, 21)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187531 entries, 0 to 187530
Data columns (total 21 columns):
 #   Column             Non-Null Count   Dtype  
---  ------             --------------   -----  
 0   Index              187531 non-null  int64  
 1   Title              187531 non-null  object 
 2   Description        184508 non-null  object 
 3   Amount(in rupees)  187531 non-null  object 
 4   Price (in rupees)  169866 non-null  float64
 5   location           187531 non-null  object 
 6   Carpet Area        106858 non-null  object 
 7   Status             186916 non-null  object 
 8   Floor              180454 non-null  object 
 9   Transaction        187448 non-null  object 
 10  Furnishing         184634 non-null  object 
 11  facing             117298 non-null  object 
 12  overlooking        106095 non-null  object 
 13  Society            77853 non-null   object 
 14  Bathroom           186703 non-null  object 
 15  Balcony            138596 non-null  object 
 16  Ca

In [7]:
df.drop(["Index"],axis=1,inplace=True)

In [8]:
total_rows = df.shape[0]
column_names = ['Title',
    'Description',
    'Amount(in rupees)',
    'Price (in rupees)',
    'location',
    'Carpet Area',
    'Status',
    'Floor',
    'Transaction',
    'Furnishing',
    'facing',
    'overlooking',
    'Society',
    'Bathroom',
    'Balcony',
    'Car Parking',
    'Ownership',
    'Super Area',
    'Dimensions',
    'Plot Area'
]

print(column_names)

['Title', 'Description', 'Amount(in rupees)', 'Price (in rupees)', 'location', 'Carpet Area', 'Status', 'Floor', 'Transaction', 'Furnishing', 'facing', 'overlooking', 'Society', 'Bathroom', 'Balcony', 'Car Parking', 'Ownership', 'Super Area', 'Dimensions', 'Plot Area']


In [9]:
for col in column_names:
    if col in df.columns:
        null_count = df[col].isnull().sum()
        percentage_null = (null_count / total_rows) * 100
        print(f"Column '{col}': {null_count} nulls ({percentage_null:.2f}%)")
    else:
        print(f"Warning: Column '{col}' not found in DataFrame.")

Column 'Title': 0 nulls (0.00%)
Column 'Description': 3023 nulls (1.61%)
Column 'Amount(in rupees)': 0 nulls (0.00%)
Column 'Price (in rupees)': 17665 nulls (9.42%)
Column 'location': 0 nulls (0.00%)
Column 'Carpet Area': 80673 nulls (43.02%)
Column 'Status': 615 nulls (0.33%)
Column 'Floor': 7077 nulls (3.77%)
Column 'Transaction': 83 nulls (0.04%)
Column 'Furnishing': 2897 nulls (1.54%)
Column 'facing': 70233 nulls (37.45%)
Column 'overlooking': 81436 nulls (43.43%)
Column 'Society': 109678 nulls (58.49%)
Column 'Bathroom': 828 nulls (0.44%)
Column 'Balcony': 48935 nulls (26.09%)
Column 'Car Parking': 103357 nulls (55.11%)
Column 'Ownership': 65517 nulls (34.94%)
Column 'Super Area': 107685 nulls (57.42%)
Column 'Dimensions': 187531 nulls (100.00%)
Column 'Plot Area': 187531 nulls (100.00%)


In [10]:
df.drop(["Dimensions","Plot Area","Super Area"],axis=1,inplace=True)

In [11]:
df.drop(["Description"],axis=1,inplace=True)

In [12]:
df['Amount(in rupees)'].value_counts()

Amount(in rupees)
Call for Price    9684
85 Lac            5264
65 Lac            4229
60 Lac            3869
70 Lac            3801
35 Lac            3369
75 Lac            3144
90 Lac            3143
40 Lac            3098
50 Lac            3006
1.75 Cr           2879
30 Lac            2790
25 Lac            2771
51 Lac            2682
45 Lac            2665
1.30 Cr           2561
22 Lac            2537
2.35 Cr           2361
23 Lac            2312
88 Lac            2310
1.20 Cr           2272
80 Lac            2253
72 Lac            2154
55 Lac            2071
95 Lac            1956
42 Lac            1852
52 Lac            1820
78 Lac            1741
1.05 Cr           1708
2.68 Cr           1655
1.55 Cr           1605
1.35 Cr           1567
1.10 Cr           1530
2.90 Cr           1491
1.92 Cr           1481
2.25 Cr           1456
1.25 Cr           1452
2.50 Cr           1378
68 Lac            1307
58 Lac            1253
31 Lac            1253
64 Lac            1210
1.60 Cr           1203
1.58 Cr           1156
18 Lac            1144
56 Lac            1144
2.10 Cr           1129
1.40 Cr           1116
1.50 Cr           1115
1.89 Cr           1095
37 Lac            1049
2.20 Cr            968
3.98 Cr            955
63 Lac             935
34 Lac             933
32.5 Lac           891
2 Cr               881
16.5 Lac           878
96 Lac             861
1.45 Cr            851
1.56 Cr            849
1.69 Cr            845
1.78 Cr            845
48 Lac             841
4.35 Cr            833
16 Lac             827
2.60 Cr            812
53 Lac             810
69 Lac             806
2.40 Cr            795
83 Lac             793
3.10 Cr            786
97.2 Lac           765
1.17 Cr            757
1 Cr               752
47 Lac             725
93 Lac             724
2.39 Cr            710
52.3 Lac           706
86.3 Lac           704
1.21 Cr            703
32 Lac             693
1.36 Cr            680
3.95 Cr            670
38 Lac             666
26.5 Lac           665
18.3 Lac           651
2.85 Cr            636
1.04 Cr            632
1.26 Cr            617
4.30 Cr            609
7 Cr               609
36 Lac             601
1.63 Cr            589
1.57 Cr            587
8.96 Cr            570
43 Lac             568
62 Lac             552
1.15 Cr            538
3.50 Cr            528
24 Lac             518
57 Lac             518
28 Lac             516
54 Lac             500
61 Lac             487
1.70 Cr            460
20 Lac             443
46 Lac             441
44 Lac             436
81 Lac             410
27 Lac             408
1.02 Cr            406
1.18 Cr            400
1.32 Cr            397
1.07 Cr            395
33 Lac             387
26 Lac             362
1.14 Cr            355
3.65 Cr            354
5 Cr               354
2.11 Cr            341
1.95 Cr            338
67.9 Lac           335
49 Lac             335
82 Lac             331
1.65 Cr            322
6.30 Cr            321
47.8 Lac           319
68.1 Lac           313
5.76 Cr            312
1.80 Cr            309
54.5 Lac           301
59 Lac             284
15 Lac             277
39 Lac             272
67 Lac             271
21 Lac             267
58.1 Lac           265
29 Lac             265
41 Lac             261
3.49 Cr            260
2.92 Cr            255
37.5 Lac           251
1.90 Cr            242
66 Lac             228
1.85 Cr            221
98 Lac             212
3 Cr               210
55.1 Lac           199
49.1 Lac           197
19 Lac             196
87 Lac             196
17 Lac             195
46.3 Lac           193
1.12 Cr            191
76 Lac             191
92 Lac             181
74 Lac             179
2.30 Cr            178
2.15 Cr            165
77 Lac             160
73 Lac             153
4 Cr               152
99 Lac             148
79 Lac             145
86 Lac             144
3.25 Cr            137
2.75 Cr            133
4.50 Cr            130
14 Lac             128
71 Lac             122
84 Lac             115
2.70 Cr            106
12 

In [13]:
df = df[df['Amount(in rupees)'] != 'Call for Price']
df.shape

(177847, 16)

In [14]:
def treat_price(x):
    if isinstance(x, float) or isinstance(x, int):
        return round(x, 2)
    else:
        if x[1] == 'Cr':
            return round(float(x[0]) * 100, 2)  # Convert Cr to Lac
        elif x[1] == 'Lac':
            return round(float(x[0]), 2)        # Already in Lac
        else:
            return None  # Unknown unit


In [15]:
df['Final Amount'] = df['Amount(in rupees)'].str.split(' ').apply(treat_price)

In [16]:
df['Final Amount'].value_counts()

Final Amount
85.0        5264
65.0        4229
60.0        3869
70.0        3801
35.0        3369
75.0        3144
90.0        3143
40.0        3098
50.0        3006
175.0       2879
30.0        2790
25.0        2771
51.0        2682
45.0        2665
130.0       2561
22.0        2537
235.0       2361
23.0        2312
88.0        2310
120.0       2272
80.0        2253
72.0        2154
55.0        2071
95.0        1956
42.0        1852
52.0        1820
78.0        1741
105.0       1708
268.0       1655
155.0       1605
135.0       1567
110.0       1530
290.0       1491
192.0       1481
225.0       1456
125.0       1452
250.0       1378
68.0        1307
58.0        1253
31.0        1253
64.0        1210
160.0       1203
158.0       1156
56.0        1144
18.0        1144
210.0       1129
140.0       1116
150.0       1115
189.0       1095
37.0        1049
220.0        968
398.0        955
63.0         935
34.0         933
32.5         891
200.0        881
16.5         878
96.0         861
145.0        851
156.0        849
169.0        845
178.0        845
48.0         841
435.0        833
16.0         827
260.0        812
53.0         810
69.0         806
240.0        795
83.0         793
310.0        786
97.2         765
100.0        764
117.0        757
47.0         725
93.0         724
239.0        710
52.3         706
86.3         704
121.0        703
32.0         693
136.0        680
395.0        670
38.0         666
26.5         665
18.3         651
285.0        636
104.0        632
126.0        617
700.0        609
430.0        609
36.0         601
163.0        589
157.0        587
896.0        570
43.0         568
62.0         552
115.0        538
350.0        528
24.0         518
57.0         518
28.0         516
54.0         500
61.0         487
170.0        460
20.0         443
46.0         441
44.0         436
81.0         410
27.0         408
102.0        406
118.0        400
132.0        397
107.0        395
33.0         387
26.0         362
114.0        355
500.0        354
365.0        354
211.0        341
195.0        338
49.0         335
67.9         335
82.0         331
165.0        322
630.0        321
47.8         319
68.1         313
576.0        312
180.0        309
54.5         301
59.0         284
15.0         277
39.0         272
67.0         271
21.0         267
58.1         265
29.0         265
41.0         261
349.0        260
292.0        255
37.5         251
190.0        242
66.0         228
185.0        221
98.0         212
300.0        210
55.1         199
49.1         197
19.0         196
87.0         196
17.0         195
46.3         193
112.0        191
76.0         191
92.0         181
74.0         179
230.0        178
215.0        165
77.0         160
73.0         153
400.0        152
99.0         148
79.0         145
86.0         144
325.0        137
275.0        133
450.0        130
14.0         128
71.0         122
84.0         115
270.0        106
12.0         105
89.0         103
280.0        101
108.0         99
149.0         99
205.0         99
425.0         93
23.5          92
320.0         92
13.0          88
97.0          87
146.0         87
27.5          84
63.5          83
600.0         82
153.0         79
10.0          79
330.0         78
128.0         78
375.0         78
265.0         77
49.5          77
17.5          76
101.0         76
33.5          74
31.5          74
39.9          74
22.5          73
550.0         71
103.0         70
360.0         68
25.5          66
245.0         65
24.5          65
18.5          64
111.0         63
84.2          63
29.5          63
122.0         62
36.5          62
59.9          62
39.5          61
138.0         61
42.5          61
38.5          58
28.5          58
91.0          58
94.0          58
106.0         56
139.0         56
43.5          56
315.0         55
340.0         54
650.0         54
47.5          53
129.0         53
19.5          53
109.0         53
35.5          52
116.0         52
21.5          51
142.0         50
34.5     

In [17]:
df.drop(["Amount(in rupees)"],axis=1,inplace=True)

In [18]:
df.drop(["Society"],axis=1,inplace=True)

In [19]:
import re

# Using a lambda function directly with .apply()
df['BHK'] = df['Title'].apply(lambda title: int(re.search(r'(\d+)\s*BHK', title, re.IGNORECASE).group(1))
                                            if re.search(r'(\d+)\s*BHK', title, re.IGNORECASE) else None)

df.head()

Title  Price (in rupees)  \
0  1 BHK Ready to Occupy Flat for sale in Srushti...             6000.0   
1  2 BHK Ready to Occupy Flat for sale in Dosti V...            13799.0   
2  2 BHK Ready to Occupy Flat for sale in Sunrise...            17500.0   
3        1 BHK Ready to Occupy Flat for sale Kasheli                NaN   
4  2 BHK Ready to Occupy Flat for sale in TenX Ha...            18824.0   

  location Carpet Area         Status         Floor Transaction  \
0    thane    500 sqft  Ready to Move  10 out of 11      Resale   
1    thane    473 sqft  Ready to Move   3 out of 22      Resale   
2    thane    779 sqft  Ready to Move  10 out of 29      Resale   
3    thane    530 sqft  Ready to Move    1 out of 3      Resale   
4    thane    635 sqft  Ready to Move  20 out of 42      Resale   

       Furnishing facing             overlooking Bathroom Balcony Car Parking  \
0     Unfurnished    NaN                     NaN        1       2         NaN   
1  Semi-Furnished   East             Garden/Park        2     NaN      1 Open   
2     Unfurnished   East             Garden/Park        2     NaN   1 Covered   
3     Unfurnished    NaN                     NaN        1       1         NaN   
4     Unfurnished   West  Garden/Park, Main Road        2     NaN   1 Covered   

              Ownership  Final Amount  BHK  
0                   NaN          42.0  1.0  
1              Freehold          98.0  2.0  
2              Freehold         140.0  2.0  
3                   NaN          25.0  1.0  
4  Co-operative Society         160.0  2.0

In [20]:
# Function to extract text based on splitting
def extract_text_after_keyword(title):
    # Prioritize 'in' as it usually precedes a more specific location/society
    if ' in ' in title:
        parts = title.split(' in ', 1) # Split only on the first ' in '
        return parts[1].strip() if len(parts) > 1 else None
    elif ' sale ' in title:
        parts = title.split(' sale ', 1) # Split only on the first ' sale '
        return parts[1].strip() if len(parts) > 1 else None
    else:
        return None # No 'in' or 'sale' found as a specific delimiter

In [21]:
# Apply the function using lambda (though a defined function is clearer here)
df['Society'] = df['Title'].apply(lambda title: extract_text_after_keyword(title))

In [22]:
df.isnull().sum()


Title                    0
Price (in rupees)     7981
location                 0
Carpet Area          76325
Status                 595
Floor                 6949
Transaction             67
Furnishing            2067
facing               65736
overlooking          75825
Bathroom               760
Balcony              47159
Car Parking          95912
Ownership            61925
Final Amount             0
BHK                    319
Society                  0
dtype: int64

In [23]:
df.drop(["Title"],axis=1,inplace=True)

In [24]:
df["location"].unique()

array(['thane', 'navi-mumbai', 'nagpur', 'mumbai', 'ahmedabad',
       'bangalore', 'chennai', 'gurgaon', 'hyderabad', 'indore', 'jaipur',
       'kolkata', 'lucknow', 'new-delhi', 'noida', 'pune', 'agra',
       'ahmadnagar', 'allahabad', 'aurangabad', 'badlapur', 'belgaum',
       'bhiwadi', 'bhiwandi', 'bhopal', 'bhubaneswar', 'chandigarh',
       'coimbatore', 'dehradun', 'durgapur', 'ernakulam', 'faridabad',
       'ghaziabad', 'goa', 'greater-noida', 'guntur', 'guwahati',
       'gwalior', 'haridwar', 'jabalpur', 'jamshedpur', 'jodhpur',
       'kalyan', 'kanpur', 'kochi', 'kozhikode', 'ludhiana', 'madurai',
       'mangalore', 'mohali', 'mysore', 'nashik', 'navsari', 'nellore',
       'palakkad', 'palghar', 'panchkula', 'patna', 'pondicherry',
       'raipur', 'rajahmundry', 'ranchi', 'satara', 'shimla', 'siliguri',
       'solapur', 'sonipat', 'surat', 'thrissur', 'tirupati', 'trichy',
       'trivandrum', 'udaipur', 'udupi', 'vadodara', 'vapi', 'varanasi',
       'vijayawada',

In [25]:
df = df.sort_values(by='Final Amount')

In [26]:
df['Price per sqft'] = df['Price (in rupees)'].interpolate(method='linear')


In [27]:
df.drop(["Price (in rupees)"],axis=1,inplace=True)

In [28]:
df.head()

location Carpet Area         Status        Floor Transaction  \
148933    badlapur         NaN  Ready to Move   5 out of 7      Resale   
165328    guwahati         NaN  Ready to Move   1 out of 2      Resale   
165332    guwahati         NaN  Ready to Move   1 out of 2      Resale   
180482  trivandrum         NaN  Ready to Move  6 out of 19      Resale   
173924       patna         NaN  Ready to Move   4 out of 6      Resale   

            Furnishing facing overlooking Bathroom Balcony Car Parking  \
148933     Unfurnished    NaN         NaN        1     NaN         NaN   
165328     Unfurnished    NaN         NaN        1     NaN         NaN   
165332     Unfurnished    NaN         NaN        1     NaN         NaN   
180482     Unfurnished    NaN         NaN        2     NaN         NaN   
173924  Semi-Furnished    NaN         NaN        2     NaN         NaN   

       Ownership  Final Amount  BHK                       Society  \
148933       NaN           1.0  1.0               Wangni Badlapur   
165328       NaN           1.0  NaN  Bishnupur, Guwahati Guwahati   
165332       NaN           1.0  NaN  Bishnupur, Guwahati Guwahati   
180482       NaN           1.0  2.0    Arcon Inspire Kazhakkottam   
173924       NaN           1.0  2.0                     Gola Road   

        Price per sqft  
148933           168.0  
165328           250.0  
165332           250.0  
180482            95.0  
173924           111.0

In [29]:
df.drop(["Carpet Area"],axis=1,inplace=True)

In [30]:
df['Status'].unique()

array(['Ready to Move', nan], dtype=object)

In [31]:
lable_map = {"Status": {"0": 0,"Ready to Move": 1,}}

df.replace(lable_map, inplace=True)

/tmp/ipython-input-31-1200789602.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace(lable_map, inplace=True)


In [32]:
df['Status'] = df['Status'].fillna('0')

In [33]:
df['Status'].unique()

array([1.0, '0'], dtype=object)

In [34]:
df['Flat Floor Number'] = df['Floor'].apply(lambda x:
    # First, check if x is not NaN and convert to string for regex matching.
    # Then, attempt to find digits at the beginning of the string using re.match.
    # If both conditions are true (not NaN and digits found), convert the captured group to int.
    # Otherwise, return np.nan.
    int(re.match(r'(\d+)', str(x)).group(1))
    if pd.notna(x) and re.match(r'(\d+)', str(x)) # Condition: not NaN AND regex match exists
    else np.nan # Value if condition is false
)

In [35]:
df['Total Floors'] = df['Floor'].apply(lambda x:
    # First, ensure x is not NaN. If it is, return np.nan immediately.
    # Otherwise, convert to string and attempt to find the pattern "out of digits".
    # If a match is found, extract and convert to int.
    # If no match or original NaN, return np.nan.
    int(re.search(r'out of (\d+)', str(x)).group(1))
    if pd.notna(x) and re.search(r'out of (\d+)', str(x))
    else np.nan
)

In [36]:
df.drop(["Floor"],axis=1,inplace=True)

In [37]:
df['Transaction'].unique()

array(['Resale', 'New Property', nan, 'Other', 'Rent/Lease'], dtype=object)

In [38]:
df['Transaction'] = df['Transaction'].fillna('0')
lable_map = {"Transaction": {"0": 0,"Other": 1,"Rent/Lease": 2,"Resale": 3,"New Property":4}}

df.replace(lable_map, inplace=True)

/tmp/ipython-input-38-2439331092.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace(lable_map, inplace=True)


In [39]:
df['Transaction'].unique()

array([3, 4, 0, 1, 2])

In [40]:
df['Furnishing'].unique()

array(['Unfurnished', 'Semi-Furnished', 'Furnished', nan], dtype=object)

In [41]:
df['Furnishing'] = df['Furnishing'].fillna('0')

lable_map = {"Furnishing": {"0": 0,"Unfurnished": 1,"Semi-Furnished": 2,"Furnished": 3}}

df.replace(lable_map, inplace=True)

/tmp/ipython-input-41-3081470212.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace(lable_map, inplace=True)


In [42]:
df['Furnishing'].unique()

array([1, 2, 3, 0])

In [43]:
df['facing'].unique()

array([nan, 'East', 'North - East', 'North', 'North - West', 'South',
       'West', 'South - East', 'South -West'], dtype=object)

In [44]:
lable_map = {
    'East': 3,
    'West': 1,
    'North': 3,
    'South': 0,
    'North - East':4 ,
    'North - West': 2,
    'South - East': 1,
    'South -West': 0
}
df.replace(lable_map, inplace=True)

/tmp/ipython-input-44-3818517351.py:11: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace(lable_map, inplace=True)


In [45]:
df['facing'].unique()

array([nan,  3.,  4.,  2.,  0.,  1.])

In [46]:
df['facing'] = df['facing'].fillna('-1')


In [47]:
df.drop(["overlooking"],axis=1,inplace=True)


In [48]:
df.head()

location Status  Transaction  Furnishing facing Bathroom Balcony  \
148933    badlapur    1.0            3           1     -1        1     NaN   
165328    guwahati    1.0            3           1     -1        1     NaN   
165332    guwahati    1.0            3           1     -1        1     NaN   
180482  trivandrum    1.0            3           1     -1        2     NaN   
173924       patna    1.0            3           2     -1        2     NaN   

       Car Parking Ownership  Final Amount  BHK                       Society  \
148933         NaN       NaN           1.0  1.0               Wangni Badlapur   
165328         NaN       NaN           1.0  NaN  Bishnupur, Guwahati Guwahati   
165332         NaN       NaN           1.0  NaN  Bishnupur, Guwahati Guwahati   
180482         NaN       NaN           1.0  2.0    Arcon Inspire Kazhakkottam   
173924         NaN       NaN           1.0  2.0                     Gola Road   

        Price per sqft  Flat Floor Number  Total Floors  
148933           168.0                5.0           7.0  
165328           250.0                1.0           2.0  
165332           250.0                1.0           2.0  
180482            95.0                6.0          19.0  
173924           111.0                4.0           6.0

In [49]:
df['Bathroom'].unique()

array(['1', '2', '3', '4', nan, '> 10', '8', '5', '7', '6', '10', '9'],
      dtype=object)

In [50]:
lable_map = {"Bathroom": {"> 10": 11}}

df.replace(lable_map, inplace=True)


In [51]:
df['Bathroom'].isna().sum()

np.int64(760)

In [52]:
df["Bathroom"].fillna(method='ffill', inplace=True)  # forward fill


/tmp/ipython-input-52-1005339307.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Bathroom"].fillna(method='ffill', inplace=True)  # forward fill
/tmp/ipython-input-52-1005339307.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Bathroom"].fillna(method='ffill', inplace=True)  # forward fill


In [53]:
df['Balcony'].unique()

array([nan, '3', '1', '2', '4', '5', '> 10', '10', '7', '6', '8', '9'],
      dtype=object)

In [54]:
df['Balcony'] = df['Balcony'].fillna('-1')

In [55]:
lable_map = {"Balcony": {"> 10": 11}}

df.replace(lable_map, inplace=True)

In [56]:
df.drop(["Car Parking"],axis=1,inplace=True)

In [57]:
df.head()

location Status  Transaction  Furnishing facing Bathroom Balcony  \
148933    badlapur    1.0            3           1     -1        1      -1   
165328    guwahati    1.0            3           1     -1        1      -1   
165332    guwahati    1.0            3           1     -1        1      -1   
180482  trivandrum    1.0            3           1     -1        2      -1   
173924       patna    1.0            3           2     -1        2      -1   

       Ownership  Final Amount  BHK                       Society  \
148933       NaN           1.0  1.0               Wangni Badlapur   
165328       NaN           1.0  NaN  Bishnupur, Guwahati Guwahati   
165332       NaN           1.0  NaN  Bishnupur, Guwahati Guwahati   
180482       NaN           1.0  2.0    Arcon Inspire Kazhakkottam   
173924       NaN           1.0  2.0                     Gola Road   

        Price per sqft  Flat Floor Number  Total Floors  
148933           168.0                5.0           7.0  
165328           250.0                1.0           2.0  
165332           250.0                1.0           2.0  
180482            95.0                6.0          19.0  
173924           111.0                4.0           6.0

In [58]:
df["Ownership"].unique()

array([nan, 'Freehold', 'Leasehold', 'Power Of Attorney',
       'Co-operative Society'], dtype=object)

In [59]:
df["Ownership"] = df["Ownership"].fillna(-1)

In [60]:
lable_map = {"Ownership": {'Freehold': 0, 'Leasehold': 1, 'Power Of Attorney': 2, 'Co-operative Society': 3}}
df.replace(lable_map, inplace=True)

/tmp/ipython-input-60-3267920443.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace(lable_map, inplace=True)


In [61]:
df["Ownership"].unique()

array([-1,  0,  1,  2,  3])

In [62]:
df['BHK'] = df['BHK'].interpolate(method='linear')

In [63]:
df["Flat Floor Number"].fillna(method='ffill', inplace=True)  # forward fill

/tmp/ipython-input-63-4290281804.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Flat Floor Number"].fillna(method='ffill', inplace=True)  # forward fill
/tmp/ipython-input-63-4290281804.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Flat Floor Number"].fillna(method='ffill', inplace=True)  # forward fill


In [64]:
df["Total Floors"].fillna(method='ffill', inplace=True)  # forward fill

/tmp/ipython-input-64-1039778094.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Total Floors"].fillna(method='ffill', inplace=True)  # forward fill
/tmp/ipython-input-64-1039778094.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Total Floors"].fillna(method='ffill', inplace=True)  # forward fill


In [65]:
df.isna().sum()

location             0
Status               0
Transaction          0
Furnishing           0
facing               0
Bathroom             0
Balcony              0
Ownership            0
Final Amount         0
BHK                  0
Society              0
Price per sqft       0
Flat Floor Number    0
Total Floors         0
dtype: int64