In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
df = pd.read_csv(r"/content/drive/MyDrive/TerraTrend_Final_Folder/TerraTrend_level2.csv")

In [ ]:
pd.set_option('display.max_rows', None)#This line sets that all rows will be shown regardless of how many there are.

pd.set_option('display.max_columns', None)#This line sets that all rows will be shown regardless of how many there are



In [ ]:
df = df.sort_values(by='Final Amount')


In [ ]:
df.shape

(160877, 13)

In [ ]:
df.head()

Title  Price (in rupees)  \
153954  1 BHK Ready to Occupy Flat for sale bambroli t...              277.0   
3544    1 BHK Ready to Occupy Flat for sale Avkar hall...             3636.0   
142213  Studio Apartment for sale in Omaxe Heights Sec...             1000.0   
67845   3 BHK Ready to Occupy Flat for sale West Marre...              279.0   
144559         1 BHK Ready to Occupy Flat for sale Campal             4667.0   

         location Carpet Area  Status  Transaction  Furnishing  facing  \
153954      surat         NaN       1            3           3       0   
3544    ahmedabad         NaN       1            3           3       0   
142213  faridabad    300 sqft       1            3           1       2   
67845   hyderabad         NaN       1            3           3       0   
144559        goa         NaN       1            3          -1       0   

        Bathroom  Balcony  Ownership Super Area  Final Amount  
153954       1.0      NaN         -1   650 sqft           1.8  
3544         1.0      1.0          0    55 sqft           2.0  
142213       1.0      1.0          0        NaN           3.0  
67845        3.0      NaN         -1  1145 sqft           3.2  
144559       2.0      NaN         -1    75 sqft           3.5

In [ ]:
df.isnull().sum()

Title                    0
Price (in rupees)     6217
location                 0
Carpet Area          68667
Status                   0
Transaction              0
Furnishing               0
facing                   0
Bathroom               579
Balcony              40921
Ownership                0
Super Area           92260
Final Amount             0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 160877 entries, 153954 to 155789
Data columns (total 13 columns):
 #   Column             Non-Null Count   Dtype  
---  ------             --------------   -----  
 0   Title              160877 non-null  object 
 1   Price (in rupees)  154660 non-null  float64
 2   location           160877 non-null  object 
 3   Carpet Area        92210 non-null   object 
 4   Status             160877 non-null  int64  
 5   Transaction        160877 non-null  int64  
 6   Furnishing         160877 non-null  int64  
 7   facing             160877 non-null  int64  
 8   Bathroom           160298 non-null  float64
 9   Balcony            119956 non-null  float64
 10  Ownership          160877 non-null  int64  
 11  Super Area         68617 non-null   object 
 12  Final Amount       160877 non-null  float64
dtypes: float64(4), int64(5), object(4)
memory usage: 17.2+ MB


In [ ]:
import re

# Using a lambda function directly with .apply()
df['BHK'] = df['Title'].apply(lambda title: int(re.search(r'(\d+)\s*BHK', title, re.IGNORECASE).group(1))
                                            if re.search(r'(\d+)\s*BHK', title, re.IGNORECASE) else None)

df.head()

Title  Price (in rupees)  \
153954  1 BHK Ready to Occupy Flat for sale bambroli t...              277.0   
3544    1 BHK Ready to Occupy Flat for sale Avkar hall...             3636.0   
142213  Studio Apartment for sale in Omaxe Heights Sec...             1000.0   
67845   3 BHK Ready to Occupy Flat for sale West Marre...              279.0   
144559         1 BHK Ready to Occupy Flat for sale Campal             4667.0   

         location Carpet Area  Status  Transaction  Furnishing  facing  \
153954      surat         NaN       1            3           3       0   
3544    ahmedabad         NaN       1            3           3       0   
142213  faridabad    300 sqft       1            3           1       2   
67845   hyderabad         NaN       1            3           3       0   
144559        goa         NaN       1            3          -1       0   

        Bathroom  Balcony  Ownership Super Area  Final Amount  BHK  
153954       1.0      NaN         -1   650 sqft           1.8  1.0  
3544         1.0      1.0          0    55 sqft           2.0  1.0  
142213       1.0      1.0          0        NaN           3.0  NaN  
67845        3.0      NaN         -1  1145 sqft           3.2  3.0  
144559       2.0      NaN         -1    75 sqft           3.5  1.0

In [ ]:
df.drop('Title', axis=1, inplace=True)

In [ ]:
df['Transaction'].unique()

array([3, 4])

In [ ]:
lable_map = {"Transaction": {3: 0,4:1}}

df.replace(lable_map, inplace=True)

In [ ]:
df['Transaction'].unique()

array([0, 1])

In [ ]:
median = df['Transaction'].median()
df['Transaction'] = df['Transaction'].fillna(median)

In [ ]:
df['Transaction'].isnull().sum()

np.int64(0)

In [ ]:
df['Furnishing'].unique()

array([ 3,  1, -1,  2])

In [ ]:
df['Furnishing'].replace(-1, np.nan, inplace=True)



In [ ]:
df['Furnishing'].unique()

array([ 3.,  1., nan,  2.])

In [ ]:
median = df['Furnishing'].median()
df['Furnishing'] = df['Furnishing'].fillna(median)

In [ ]:
df['facing'].unique()

array([0, 2, 3, 4, 5, 1])

In [ ]:
df['facing'].isnull().sum()

np.int64(0)

In [ ]:
df['Status'].unique()

array([1, 0])

In [ ]:
df['Status'].isna().sum()

np.int64(0)

In [ ]:
df['Ownership'].unique()

array([-1,  0,  1,  2,  3])

In [ ]:
df['Ownership'].replace(-1, np.nan, inplace=True)

In [ ]:
median = df['Ownership'].median()
df['Ownership'] = df['Ownership'].fillna(median)


In [ ]:
df['Bathroom'].unique()

array([ 1.,  3.,  2.,  4., nan,  8.,  5.,  7., 10.,  6., 11.,  9.])

In [ ]:
#df['Bathroom'] = df.groupby('BHK')['Bathroom'].transform(lambda x: x.fillna(method='ffill'))
#df['Bathroom'] = df.groupby('BHK')['Bathroom'].transform(lambda x: x.fillna(method='ffill').fillna(method='bfill'))
median_bathroom = df['Bathroom'].median()
df['Bathroom'] = df['Bathroom'].fillna(median)

In [ ]:
df['Bathroom'].unique()

array([ 1.,  0.,  3.,  2.,  4.,  8.,  5.,  7., 10.,  6., 11.,  9.])

In [ ]:
df['Balcony'].unique()

array([nan,  1.,  2.,  3.,  4., 11.,  5.,  7.,  6., 10.,  8.,  9.])

In [ ]:
#df['Balcony'] = df.groupby('BHK')['Balcony'].transform(lambda x: x.fillna(method='ffill'))
median_bathroom = df['Balcony'].median()
df['Balcony'] = df['Balcony'].fillna(median)

In [ ]:
df['Balcony'].unique()

array([ 0.,  1.,  2.,  3.,  4., 11.,  5.,  7.,  6., 10.,  8.,  9.])

In [ ]:
df.head()

Price (in rupees)   location Carpet Area  Status  Transaction  \
153954              277.0      surat         NaN       1            0   
3544               3636.0  ahmedabad         NaN       1            0   
142213             1000.0  faridabad    300 sqft       1            0   
67845               279.0  hyderabad         NaN       1            0   
144559             4667.0        goa         NaN       1            0   

        Furnishing  facing  Bathroom  Balcony  Ownership Super Area  \
153954         3.0       0       1.0      0.0        0.0   650 sqft   
3544           3.0       0       1.0      1.0        0.0    55 sqft   
142213         1.0       2       0.0      0.0        0.0        NaN   
67845          3.0       0       3.0      0.0        0.0  1145 sqft   
144559         2.0       0       2.0      1.0        0.0    75 sqft   

        Final Amount  BHK  
153954           1.8  1.0  
3544             2.0  1.0  
142213           3.0  NaN  
67845            3.2  3.0  
144559           3.5  1.0

In [ ]:
df.isnull().sum()

Price (in rupees)     6217
location                 0
Carpet Area          68667
Status                   0
Transaction              0
Furnishing               0
facing                   0
Bathroom                 0
Balcony                  0
Ownership                0
Super Area           92260
Final Amount             0
BHK                    238
dtype: int64

In [ ]:
mean = df['BHK'].mean()
df['BHK'] = df['BHK'].fillna(mean)

In [ ]:
# rename columns
df.rename(columns={'Carpet Area':'Carpet Area in sqft'},inplace=True)

In [ ]:
df['Carpet Area in sqft'] = df['Carpet Area in sqft'].apply(lambda x:
    int(re.search(r'(\d+)', str(x)).group(1)) # Extract digits and convert to int
    if pd.notna(x) and re.search(r'(\d+)', str(x)) # Check if not NaN and digits exist
    else np.nan # If NaN or no digits found, set to NaN
)

In [ ]:
def convert_to_sqft(x):
    """
    Converts carpet area to square feet.
    Handles 'sqft' and 'sqyrd' units.
    """
    # Handle NaN values
    if pd.isna(x):
        return np.nan

    x_str = str(x).lower()

    # Check for 'sqyrd' or 'sqyd'
    if 'sqyrd' in x_str or 'sqyd' in x_str:
        match = re.search(r'(\d+)', x_str)
        if match:
            # Convert to int and then multiply by 9 (1 sq yard = 9 sq feet)
            return int(match.group(1)) * 9
        else:
            return np.nan
    else:
        # Assume it's 'sqft' and extract the number
        match = re.search(r'(\d+)', x_str)
        if match:
            return int(match.group(1))
        else:
            return np.nan

# Apply the new function to the column
df['Super Areain sqft'] = df['Super Area'].apply(convert_to_sqft)

In [ ]:
df.head()

Price (in rupees)   location  Carpet Area in sqft  Status  \
153954              277.0      surat                  NaN       1   
3544               3636.0  ahmedabad                  NaN       1   
142213             1000.0  faridabad                300.0       1   
67845               279.0  hyderabad                  NaN       1   
144559             4667.0        goa                  NaN       1   

        Transaction  Furnishing  facing  Bathroom  Balcony  Ownership  \
153954            0         3.0       0       1.0      0.0        0.0   
3544              0         3.0       0       1.0      1.0        0.0   
142213            0         1.0       2       0.0      0.0        0.0   
67845             0         3.0       0       3.0      0.0        0.0   
144559            0         2.0       0       2.0      1.0        0.0   

       Super Area  Final Amount       BHK  Super Areain sqft  
153954   650 sqft           1.8  1.000000              650.0  
3544      55 sqft           2.0  1.000000               55.0  
142213        NaN           3.0  2.617391                NaN  
67845   1145 sqft           3.2  3.000000             1145.0  
144559    75 sqft           3.5  1.000000               75.0

In [ ]:
df['Carpet Area in sqft'] = df.groupby('BHK')['Carpet Area in sqft'].transform(lambda x: x.fillna(x.median()))

In [ ]:
df['Super Area in sqft'] = df.groupby('BHK')['Super Areain sqft'].transform(lambda x: x.fillna(x.median()))

In [ ]:
df.drop(['Super Areain sqft','Super Area'] ,axis=1, inplace=True)

In [ ]:
df['Price (in rupees)'] = df.groupby('location')['Price (in rupees)'].transform(lambda x: x.interpolate(method='linear'))

In [ ]:
df.isna().sum()

Price (in rupees)      3
location               0
Carpet Area in sqft    7
Status                 0
Transaction            0
Furnishing             0
facing                 0
Bathroom               0
Balcony                0
Ownership              0
Final Amount           0
BHK                    0
Super Area in sqft     0
dtype: int64

In [ ]:
df.dropna(inplace=True)